import {
	eighthTemplate,
	fifthTemplate,
	firstTemplate,
	fourthTemplate,
	ninthTemplate,
	secondTemplate,
	seventhTemplate,
	sixthTemplate,
	tenthTemplate,
	thirdTemplate,
} from './templates'

export const sections = [
	{
		title: 'Модуль 1: Арифметика',
		description: 'Основы сложения, вычитания, умножения и деления чисел.',
		questionTemplates: [
			firstTemplate,
			secondTemplate,
			thirdTemplate,
			fourthTemplate,
			fifthTemplate,
			sixthTemplate,
			seventhTemplate,
			eighthTemplate,
			ninthTemplate,
			tenthTemplate,
		],
	},
	{
		title: 'Модуль 2: Геометрия',
		description: 'Основные геометрические фигуры и их свойства.',
		questionTemplates: [
			firstTemplate,
			secondTemplate,
			thirdTemplate,
			fourthTemplate,
			fifthTemplate,
			sixthTemplate,
			seventhTemplate,
			eighthTemplate,
			ninthTemplate,
			tenthTemplate,
		],
	},
	{
		title: 'Модуль 3: Алгебра',
		description: 'Переменные, уравнения и функции.',
		questionTemplates: [
			firstTemplate,
			secondTemplate,
			thirdTemplate,
			fourthTemplate,
			fifthTemplate,
			sixthTemplate,
			seventhTemplate,
			eighthTemplate,
			ninthTemplate,
			tenthTemplate,
		],
	},
]
